### ISSUE TITLE
question about the test code

### ISSUE THREAD

**Issue by xinli2008** [Zj-BinXia/DiffIR#16]
Thank you for your nice job in IR, i came across a problem when `testing on CelebA dataset`

[2023-10-31 16:09:00,318][__main__][CRITICAL] - Prediction failed due to [Errno 2] No such file or directory: '/mnt/bn/xiabinpaint/ICCV-Inpainting/code-final/DiffIR-inpainting-final/celeba-ta.pth':
Traceback (most recent call last):
  File "/mnt/DiffIR/DiffIR-inpainting/predict.py", line 57, in main
    model = load_checkpoint(train_config, checkpoint_path, strict=False, map_location='cpu')
  File "/mnt/DiffIR/DiffIR-inpainting/saicinpainting/training/trainers/__init__.py", line 29, in load_checkpoint
    model: torch.nn.Module = make_training_model(train_config)
  File "/mnt/DiffIR/DiffIR-inpainting/saicinpainting/training/trainers/__init__.py", line 25, in make_training_model
    return cls(config, **kwargs)
  File "/mnt/DiffIR/DiffIR-inpainting/saicinpainting/training/trainers/defaultS2.py", line 34, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/DiffIR/DiffIR-inpainting/saicinpainting/training/trainers/baseS2.py", line 81, in __init__
    load_network(self.generator,generatorS2_path,strict=False)
  File "/mnt/DiffIR/DiffIR-inpainting/saicinpainting/training/trainers/baseS2.py", line 31, in load_network
    load_net = torch.load(load_path)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/bn/xiabinpaint/ICCV-Inpainting/code-final/DiffIR-inpainting-final/celeba-ta.pth'  @Zj-BinXia

**Comment by xinli2008** [comment]
I do not train the model and just download the pretrained model in experiments folder and do the predict.py

**Comment by xinli2008** [comment]
And whether there is inference code to generate repaired images given original images and mask images?

**Comment by Zj-BinXia** [comment]
The inpainting code is built don Lama: https://github.com/advimman/lama. You can see it for more information

**Comment by akankshasingh25** [comment]
Hey @xinli2008, did you solve the issue? If yes, can you help me too? Where did you get the weights from?
