### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/models/lpips_models/vgg.pth'

### ISSUE THREAD

**Issue by WJDNJSDJ** [Zj-BinXia/DiffIR#23]
Hello, thank you very much for your contribution! I encountered this issue during debugging and am unsure how to resolve it. I kindly request your guidance. Wishing you a joyful life and successful endeavors!
[__main__][CRITICAL] - Training failed due to [Errno 2] No such file or directory: '/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/models/lpips_models/vgg.pth':
Traceback (most recent call last):
  File "bin/train.py", line 50, in main
    training_model = make_training_model(config)
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/training/trainers/__init__.py", line 25, in make_training_model
    return cls(config, **kwargs)
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/training/trainers/defaultS1.py", line 32, in __init__
    super().__init__(*args, **kwargs)
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/training/trainers/baseS1.py", line 79, in __init__
    self.val_evaluator = make_evaluator(**self.config.evaluator)
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/evaluation/__init__.py", line 16, in make_evaluator
    metrics['lpips'] = LPIPSScore()
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/evaluation/losses/base_loss.py", line 109, in __init__
    self.score = PerceptualLoss(model=model, net=net, model_path=model_path,
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/evaluation/losses/lpips.py", line 26, in __init__
    self.model.initialize(model=model, net=net, use_gpu=use_gpu, colorspace=colorspace,
  File "/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/saicinpainting/evaluation/losses/lpips.py", line 294, in initialize
    self.net.load_state_dict(torch.load(model_path, **kw), strict=False)
  File "/home/liu/anaconda3/envs/DIFFIR/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/liu/anaconda3/envs/DIFFIR/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/liu/anaconda3/envs/DIFFIR/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/liu/ZZB/DiffIR-master/DiffIR-inpainting/models/lpips_models/vgg.pth'

**Comment by Zj-BinXia** [comment]
The VGG model should automatically download when running. Please check your network connection.

**Comment by WJDNJSDJ** [comment]
Thank you very much for your answer, it has been resolved.
