### ISSUE TITLE
'DiffIRGANS2Model' object has no attribute 'model_Es1'

### ISSUE THREAD

**Issue by yongsongH** [Zj-BinXia/DiffIR#28]
Thank you for your excellent work!

When trying the upsampling factor is 2 and loading the pre-trained model, I met the following problem.
`Traceback (most recent call last):
  File "DiffIR/train.py", line 15, in <module>
    train_pipeline(root_path)
  File "/DiffIR/DiffIR-SRGAN/DiffIR/train_pipeline.py", line 185, in train_pipeline
    model.optimize_parameters(current_iter)
  File "/DiffIR/DiffIR-SRGAN/DiffIR/models/DiffIR_GAN_S2_model.py", line 116, in optimize_parameters
    _, S1_IPR = self.model_Es1(self.lq,self.gt)`
I would appreciate it if you could kindly give me some advice about this.

Thanks in advance.

**Comment by yongsongH** [comment]
Appreciate your reply! I'll confirm later, if this works in my program and updates will be shared promptly :)

**Comment by yongsongH** [comment]
Works! Thanks again for your help!
