### ISSUE TITLE
Data Class Loading Issue

### ISSUE THREAD

**Issue by Trevor-Philips-cbd** [Zj-BinXia/DiffIR#29]
Has anyone encountered this problem? It seems that the dataset class cannot be registered when loading.

Traceback (most recent call last):
  File "DiffIR/train.py", line 15, in <module>
    train_pipeline(root_path)
  File "/mnt/sdc/bdc/DiffIR-master/DiffIR-demotionblur/DiffIR/train_pipeline.py", line 121, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "/mnt/sdc/bdc/DiffIR-master/DiffIR-demotionblur/DiffIR/train_pipeline.py", line 36, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/home/bdc/anaconda3/envs/pytorch/lib/python3.7/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/home/bdc/anaconda3/envs/pytorch/lib/python3.7/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'DeblurPairedDataset' found in 'dataset' registry!"
Name DeblurPairedDataset is not found, use name: DeblurPairedDataset_basicsr!
Traceback (most recent call last):
  File "DiffIR/train.py", line 15, in <module>
    train_pipeline(root_path)
  File "/mnt/sdc/bdc/DiffIR-master/DiffIR-demotionblur/DiffIR/train_pipeline.py", line 121, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "/mnt/sdc/bdc/DiffIR-master/DiffIR-demotionblur/DiffIR/train_pipeline.py", line 36, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/home/bdc/anaconda3/envs/pytorch/lib/python3.7/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/home/bdc/anaconda3/envs/pytorch/lib/python3.7/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'DeblurPairedDataset' found in 'dataset' registry!"

**Comment by yanmengyi** [comment]
me too

**Comment by Wxsxulin** [comment]
我也是
