### ISSUE TITLE
Does this project work only for Linux devices only? 

### ISSUE THREAD

**Issue by yaman-77** [Zj-BinXia/DiffIR#34]
I'm trying to utilize the motion deblur work on Windows 11, however, it is not working. I tried to run the codes using WSL2 and Ubuntu 22.04 (using Oracle virtual machine) but I'm still facing several issues. The current main issue is related to importing DiffIR in other files, please see the following: 

    from DiffIR.train_pipeline import train_pipeline
ModuleNotFoundError: No module named 'DiffIR'
[2024-01-10 14:41:03,177] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 992) of binary: /home/yaman/anaconda3/bin/python3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaman/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
DiffIR/train.py FAILED

**Please note that I ran the ((bash pip.sh)) command before running one of the trainS1.sh or trainS2.sh scripts.** 

Is it related somehow to using WSL or VM based Ubuntu?

**Comment by yaman-77** [comment]
> You can try pip uninstall basicsr and sh pip.sh

I tried but unfortunately, I had the same issue. In fact, basicsr won't install when the command sh pip.sh is used. 

Looking in indexes: http://pypi.douban.com/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff78c1e5110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/basicsr/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff78c1e75d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/basicsr/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff78c1e7ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/basicsr/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff78c1bc910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/basicsr/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff78c1bd310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /pypi/simple/basicsr/
ERROR: Could not find a version that satisfies the requirement basicsr (from versions: none)
ERROR: No matching distribution found for basicsr

Do you think it is a problem related to not using a full Linux distribution instead of WSL and VMs?
