### ISSUE TITLE
单卡训练报错

### ISSUE THREAD

**Issue by zdyshine** [Zj-BinXia/DiffIR#36]
Traceback (most recent call last):
  File "DiffIR/train.py", line 15, in <module>
    train_pipeline(root_path)
  File "/DiffIR/DiffIR-RealSR/DiffIR/train_pipeline.py", line 185, in train_pipeline
    model.optimize_parameters(current_iter)
  File "/DiffIR/DiffIR-RealSR/DiffIR/models/DiffIR_S2_model.py", line 408, in optimize_parameters
    _, pred_IPR_list = self.net_g.module.diffusion(self.lq,S1_IPR[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DiffIRS2' object has no attribute 'module'

多卡训练时会有module这个属性，是必须使用多卡训练吗？

**Comment by Zj-BinXia** [comment]
You can change _, pred_IPR_list = self.net_g.module.diffusion(self.lq,S1_IPR[0]) to _, pred_IPR_list = self.net_g.diffusion(self.lq,S1_IPR[0])
