### ISSUE TITLE
NCCL timing out

### ISSUE THREAD

**Issue by JiaqiShi-Stu** [Zj-BinXia/DiffIR#39]
训练RealSR到一半，到5000iter时开始执行val，然后报错,

[E ProcessGroupNCCL.cpp:566] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803936 millisecond
s before timing out.
Traceback (most recent call last):
File "DiffIR/train.py", line 15, in <module>
train_pipeline(root_path)
File "/data/sjq/SR/DiffIR/DiffIR-RealSR/DiffIR/train_pipeline.py", line 185, in train_pipeline
model.optimize_parameters(current_iter)
File "/data/sjq/SR/DiffIR/DiffIR-RealSR/DiffIR/models/DiffIR_S1_model.py", line 329, in optimize_parameters
self.log_dict = self.reduce_loss_dict(loss_dict)
File "/home/ikun/miniconda3/envs/diffir/lib/python3.8/site-packages/basicsr/models/base_model.py", line 371, in reduce_loss_dict
torch.distributed.reduce(losses, dst=0)
File "/home/ikun/miniconda3/envs/diffir/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1383, in reduce
work = default_pg.reduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 994987) of binary: /home/ikun/miniconda3/envs/diffir/bin/python3\

我是用两张4090训练的，是不是显存不够导致超时了？

**Comment by blitu12345** [comment]
how to resolve it please help
