### ISSUE TITLE
The provided model is not compatible with the code

### ISSUE THREAD

**Issue by ShijianXu** [Zj-BinXia/DiffIR#6]
I am trying to test DiffIR-SRGAN. I set the model as instructed in the README file, but encountered with the following error. Could you pls check the model compatibility? Thanks!

```
......
2023-09-06 08:03:51,010 INFO: Loading DiffIRS2 model from experiments/SISR-DiffIRS2-GAN.pth, with param key: [params_ema].
2023-09-06 08:03:51,364 INFO: Network [DiffIRS1] is created.
2023-09-06 08:03:53,088 INFO: Loading DiffIRS1 model from experiments/SISR-DiffIRS1.pth, with param key: [params_ema].
Traceback (most recent call last):
  File "DiffIR/test.py", line 11, in <module>
    test_pipeline(root_path)
  File "/cluster/....../my_envs/diffir/lib64/python3.8/site-packages/basicsr/test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "/cluster/....../my_envs/diffir/lib64/python3.8/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/cluster/....../DiffIR/DiffIR-SRGAN/DiffIR/models/DiffIR_GAN_S2_model.py", line 43, in __init__
    self.model_Eta = self.net_g_S1.module.E
  File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'DiffIRS1' object has no attribute 'module'
```

Also, in requirements.txt, the requirement for torch is `torch>=1.7`, but it seems that `nn.PixelUnshuffle` is only availble for `torch>=1.8`, see [this](https://github.com/FanChiMao/HWMNet/issues/1#issuecomment-1066604302).

Best regards.

**Comment by Zj-BinXia** [comment]
run this command:
CUDA_VISIBLE_DEVICES=0 python3  DiffIR/test.py -opt options/test_DiffIRS2_GAN_x4.yml 
specify CUDA_VISIBLE_DEVICES

**Comment by Zj-BinXia** [comment]
or you can change File "/cluster/....../DiffIR/DiffIR-SRGAN/DiffIR/models/DiffIR_GAN_S2_model.py", line 43
self.model_Eta = self.net_g_S1.E
and run 
python3 DiffIR/test.py -opt options/test_DiffIRS2_GAN_x4.yml

**Comment by ShijianXu** [comment]
Thanks a lot! Cahnging File "/cluster/....../DiffIR/DiffIR-SRGAN/DiffIR/models/DiffIR_GAN_S2_model.py", line 43
`self.model_Eta = self.net_g_S1.E` fixed the problem.
