### ISSUE TITLE
终端显示'DiffIRS1' object has no attribute 'module'

### ISSUE THREAD

**Issue by Justified4** [Zj-BinXia/DiffIR#65]
进行train_DiffIRS2_GANv2.sh时报错
Traceback (most recent call last):
  File "DiffIR/train.py", line 15, in <module>
    train_pipeline(root_path)
  File "/root/autodl-tmp/DiffIR/train_pipeline.py", line 125, in train_pipeline
    model = build_model(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/root/autodl-tmp/DiffIR/models/DiffIR_GAN_S2_model.py", line 44, in __init__
    self.model_Es1 = self.net_g_S1.module.E
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DiffIRS1' object has no attribute 'module'

**Comment by BrainMapping-hub** [comment]
Have you solved this problem? I encountered the same problem.

**Comment by So-cean** [comment]
same problem

**Comment by So-cean** [comment]
using `self.model_Es1 = self.net_g_S1.E` instead of `self.model_Es1 = self.net_g_S1.module.E`
